### ISSUE TITLE
HW2ISSUE#8 Sidebar structure advice

### ISSUE THREAD

**Issue by DennyTim** [arjuncv7/Homework#23]
https://github.com/arjuncv7/Homework/blob/56b95e1ea78a606834b2053e353f15a75aa52aed/Homework2/index.html#L30

Your nav menu can be rewritten in the next way:

```html
<aside class="sidebar">
                <a href="#" class="sidebar__item">Ramda</a>
                <a href="#" class="sidebar__item">Why Ramda?</a>
                <a href="#" class="sidebar__item">What's Different?</a>
                <a href="#" class="sidebar__item">Introduction</a>
                <a href="#" class="sidebar__item">Philosophy</a>
</aside>
```

```css
.sidebar {
    width: 344px;
    margin-top: 51px;
    border: 1px solid black;
    list-style: none;
    align-self: start;
}

.sidebar__item:hover {
    padding-left: 70px;
    transition: All 0.4s ease;
    color: black;
    background: rgb(220, 220, 220);
}

.sidebar__item {
    display: block;
    padding-left: 44px;
    font-size: 27px;
    padding-top: 20px;
    padding-bottom: 20px;
    text-decoration: none;
    color: rgb(70, 87, 99);
}
```

without any nested tags and height property that is able to break the content view after its increasing
