### ISSUE TITLE
Issue #9

### ISSUE THREAD

**Issue by DennyTim** [arjuncv7/Homework#9]
https://github.com/arjuncv7/Homework/blob/5a426e9adaccdaec230b86e532f6313ba4f2a08c/index.html#L14

Better to bring a special container for each section of the page.
If you wanna use a margin to align the content for the page, you need to use the following structure:
```html
<header class="...">
   <div class="container">...</div>
</header>
<main class="...">
   <div class="container">...</div>
</main >
<footer class="...">
   <div class="container">...</div>
</footer>
```
```css
.container {
    width: 960px;
    margin: 0 auto;
    text-align: center; /* can be used optionally if you wanna align the whole section */
}
```
